# tasks file
---
- name: repository
  import_tasks: repository.yml
  tags:
    - configuration
    - r
    - r-repository

- name: install
  import_tasks: install.yml
  tags:
    - configuration
    - r
    - r-install

- name: packages
  import_tasks: packages.yml
  tags:
    - configuration
    - r
    - r-packages
